locales:
  default: en_US
  supported:
    - ar
    - de
    - en_GB
    - es
    - fr_CA
    - fr_FR
    - it
    - ja
    - nl
    - pl
    - pt
    - ru
    - sv
    - zh_CN
    - zh_HK

bundles:
  - path: .
    extension: properties
    default_locale: en_US
  - path: src/main/resources
    extension: json

io:
  out:
    generator: translations.extensions.io_xls.XlsExporter
    name: translations
    mapping:
      fr_CA: fr
      fr_FR: fr
      en_US: ~
      en_GB: ~
  in:
    importer: translations.extensions.io_xls.XlsImporter
    package: translations-in/translations.zip
    mapping:
      fr:
        - fr_CA
        - fr_FR
      __SNAPSHOT__:
        - en_GB
